import { authProvider } from "@/providers/auth-provider";
import { dataProvider } from "@/providers/data-provider";
import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { ReactNode, Suspense } from "react";
import { Providers } from "./provider";
import { cookies } from "next/headers";
import "./global.css";
import { ThemedLayoutContextProvider } from "@refinedev/chakra-ui";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: { icon: "/favicon.ico" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  // const defaultMode = theme?.value === "dark" ? "dark" : "dark";
  return (
    <html lang="en">
      <body style={{ minHeight: "100svh" }}>
        <Suspense>
          <RefineKbarProvider>
            <Providers>
              <Refine
                routerProvider={routerProvider}
                authProvider={authProvider}
                dataProvider={dataProvider}
                resources={[
                  {
                    name: "projects",
                    list: "/projects",
                    create: "/projects/create",
                    edit: "/projects/edit/:id",
                    show: "/projects/show/:id",
                    meta: { canDelete: true, idColumnName: "project_id" },
                  },
                  {
                    name: "locations",
                    list: "/locations",
                    create: "/locations/create",
                    edit: "/locations/edit/:id",
                    show: "/locations/show/:id",
                    meta: { canDelete: true, idColumnName: "locatin_id" },
                  },
                  {
                    name: "configs",
                    list: "/configs",
                    meta: { idColumnName: "config_id" },
                  },
                ]}
                options={{
                  syncWithLocation: true,
                  warnWhenUnsavedChanges: true,
                  useNewQueryKeys: true,
                  projectId: "RFzO6Z-1fZKgi-ISO87J",
                }}
              >
                <>{children}</>
                <RefineKbar />
              </Refine>
            </Providers>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
